CREATE SCHEMA konoha;

USE konoha;

CREATE TABLE IF NOT EXISTS NINJA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(255) NOT NULL,
	RANGO VARCHAR(255) NOT NULL,
	ALDEA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MISION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DESCRIPCION VARCHAR(255),
	RANGO VARCHAR(255),
	RECOMPENSA VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MISION_NINJA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ID_NINJA INT,
	FOREIGN KEY(ID_NINJA) REFERENCES NINJA(ID),
	ID_MISION INT,
	FOREIGN KEY (ID_MISION) REFERENCES MISION(ID),
	FECHA_INICIO DATE,
	FECHA_FIN DATE
);

CREATE TABLE IF NOT EXISTS HABILIDAD (
	ID_NINJA INT PRIMARY KEY,
	FOREIGN KEY(ID_NINJA) REFERENCES NINJA(ID),
	NOMBRE VARCHAR(255),
	DESCRIPCION VARCHAR(255)
);

