USE konoha;

INSERT INTO NINJA (NOMBRE, RANGO, ALDEA) VALUES ('WARRIOR', 'APRENDIZ', 'MINI VILLAGE');
INSERT INTO NINJA (NOMBRE, RANGO, ALDEA) VALUES ('FIGHTER', 'SOLDADO', 'SUNNY VILLAGE');
INSERT INTO NINJA (NOMBRE, RANGO, ALDEA) VALUES ('HERO', 'MAESTRO', 'RIVER VILLAGE');

INSERT INTO HABILIDAD (ID_NINJA, NOMBRE, DESCRIPCION) VALUES (1, 'INVISIBILIDAD', 'SE VUELVE INVISIBLE');
INSERT INTO HABILIDAD (ID_NINJA, NOMBRE, DESCRIPCION) VALUES (2, 'FUERZA', 'FUERZA INVENCIBLE');
INSERT INTO HABILIDAD (ID_NINJA, NOMBRE, DESCRIPCION) VALUES (3, 'INVISIBILIDAD', 'CORRE MUY RÁPIDO');

INSERT INTO MISION (DESCRIPCION, RANGO, RECOMPENSA) VALUES ('MATAR UN ENEMIGO','APRENDIZ','100');
INSERT INTO MISION (DESCRIPCION, RANGO, RECOMPENSA) VALUES ('MATAR TRES ENEMIGOS','SOLDADO','300');
INSERT INTO MISION (DESCRIPCION, RANGO, RECOMPENSA) VALUES ('MATAR DIEZ ENEMIGOS','MAESTRO','600');

INSERT INTO MISION_NINJA (ID_NINJA, ID_MISION) VALUES (1,1);
INSERT INTO MISION_NINJA (ID_NINJA, ID_MISION) VALUES (2,2);
INSERT INTO MISION_NINJA (ID_NINJA, ID_MISION) VALUES (3,3);



